development:
  adapter: postgresql
  encoding: unicode
  database: omrails_development
  pool: 5
  username: omrails
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: omrails_production
  pool: 5
  username: omrails
  password:  

test:
  adapter: postgresql
  encoding: unicode
  database: omrails_test
  pool: 5
  username: omrails
  password: 
